# Strided arrays

Vectors are 1 dimensional mathematical objects, which can be represented with numpy arrays.

The vector $x = \begin{bmatrix}1 \\ 2 \\ 3\end{bmatrix}$ can naturally be stored in an array,

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


We could also store the vector in an array where the values are spaced 2 apart,

In [3]:
x = np.array([1, 0, 2, 0, 3, 0])
print(x)

[1 0 2 0 3 0]


In this case, to recover the values of the vector we need to slice the array using a stride value of 2.

In [4]:
x[::2]

array([1, 2, 3])

The stride value is also called the `increment` value, and is named with a correspondance to the array. For the array `x`, we would call the `increment` value `incx`. We can use this value to access the vector values

In [5]:
incx = 2
x[::incx]

array([1, 2, 3])

The array can also be stored with extra unused values added on the end,

In [6]:
x = np.array([1, 0, 2, 0, 3, 0, 0, 0])
print(x)

[1 0 2 0 3 0 0 0]


In this case we need to know the size of the vector, $N$, as well as the spacing in order to recover the vector values. 

In [7]:
N = 3
incx = 2
x[:N*incx:incx]

array([1, 2, 3])

Another way of storing the values of $x$ is with the values stored in reverse order in an array.

In [8]:
x = np.array([3, 2, 1])
print(x)

[3 2 1]


This storage pattern corresponds to an `increment` of `-1`, so we can recover the values of the vector as such:

In [9]:
incx = -1
x[::incx]

array([1, 2, 3])

If we include padding in the array then we also need to know $N$, the size of the vector, in order to recover the values.

In [10]:
x = np.array([3, 2, 1, 0, 0, 0])
N = 3
incx = -1
x[N-1::incx]

array([1, 2, 3])

Finally, we can store the values of `x` in reverse order with a fixed spacing, say 2, and padding at the end of the array.

In [11]:
x = np.array([3, 0, 2, 0, 1, 0, 0, 0])
N = 3
incx = -2
x[(N-1)*(-incx)::incx]

array([1, 2, 3])

In general, to recover the vector values of $x$ from a padded array `x`, we need to know the size of the vector $N$, and the spacing of the array values, `incx`. From these we can compute a `slice` object which will recover the vector values from the array `x`.

In [12]:
def slice_(N, inc):
    if inc > 0:
        return slice(None, N * inc, inc)
    else:
        return slice(-(N - 1) * inc, None, inc)

N = 3
# Standard array
x = np.array([1, 2, 3])
print(x[slice_(N, 1)])

# Padded array
x = np.array([1, 2, 3, 0, 0, 0])
print(x[slice_(N, 1)])

# Padded, strided array
x = np.array([1, 0, 2, 0, 3, 0, 0, 0])
print(x[slice_(N, 2)])

# Reversed array
x = np.array([3, 2, 1])
print(x[slice_(N, -1)])

# Reversed, padded array
x = np.array([3, 2, 1, 0, 0, 0])
print(x[slice_(N, -1)])

# Reversed, padded, strided array
x = np.array([3, 0, 2, 0, 1, 0, 0, 0, 0])
print(x[slice_(N, -2)])


[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]
